### ISSUE TITLE
CO2 Product - Token

### ISSUE THREAD

**Issue by BennerLukas** [michael-spengler/aktuelle-data-science-entwicklungen-2-wwi19dsab#3]
Jedes Produkt erhält basierend auf Tokens der Vorprodukte einen Token hinter dem Informationen über den CO2-Ausstoß gespeichert werden. Dadurch sind transparente Lieferketten möglich.

Erweiterbar mit Infos über Produktionsbedingungen, Menschenrechte etc.

--> Kontrolle über Netzwerk (Plausibilitätsberechnungen oder so?)

(wird wahrscheinlich nicht von meiner Gruppe bearbeitet, kann also übernommen werden)

**Comment by michael-spengler** [comment]
optional: Die Daten dazu könnten wir auf der Ethereum Blockchain speichern.

Ein möglicher Aspekt
Zertifikate als NFTs

Welche Organisation soll berechtigt sein diese Zertifikate auszugeben... 

Ein DAO könnte als solche Organisation dienen.
